### ISSUE TITLE
Completed part a of homework assignment 03

### ISSUE THREAD

**Issue by Severin-Ek** [ds4owd-001/md-03-assignments-Severin-Ek#1]
Dear @larnsce @mianzg and @sskorik01,
I want to inform you that I have completed part a of homework assignment 03. 
I case you find any problem in checking the assignment, kindly let me know. 

Best regards,
Sévérin

**Comment by larnsce** [comment]
Thank you for completing the assignment @Severin-Ek. I have had a look at your code and it looks great. Well done. 👏🏼

I will close the issue now.
