### ISSUE TITLE
Completed module 3 assignments

### ISSUE THREAD

**Issue by Severin-Ek** [ds4owd-001/md-03-assignments-Severin-Ek#2]
Dear @larnsce @mianzg and @sskorik01,
I want to inform you that I have completed the module 3 assignments. 

Regards,
Sévérin

**Comment by sskorik01** [comment]
Hi Sévérin, 

Congratulations for working through the module 3 assignments. It seems like you understood the concepts of the course well. Here is a small detail for next time.

When you have several options for a variable such as 

```{r}
 island == "Dream" | island == "Biscoe"
```

you can replace it by 

```{r}
 island %in% c("Dream", "Biscoe")
```
such that it's shorter :)

**Comment by Severin-Ek** [comment]
Hello sskoriko1,
Thanks for your comments on my assignment, and the suggested methods. It is
really helpful.
When I was tryingto get the code from ChatGPT, I got it but I
didn'tunderstand it that way.

Yesterday, I was not able to join the Module 4 session due to a job
interview scheduledat the same time.
But I will catch up over theweek.

Thanks for the support.

Best wishes,

.......
